.test-script-template:
   script:
     - tar xzf gmx-build.tar.gz
     - tar xzf gmx-install.tar.gz
     - tar xzf gmx-regressiontests.tar.gz
     - cd $BUILD_DIR
     - ctest -D ExperimentalTest --output-on-failure
     - xsltproc scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
     - cd ..
     - source $INSTALL_DIR/bin/GMXRC
   artifacts:
     reports:
       junit: $BUILD_DIR/JUnitTestResults.xml
   # TODO Why is this file in junit and paths?
   artifacts:
       paths:
           - $BUILD_DIR/JUnitTestResults.xml
       when: always
       expire_in: 1 week
