.variables-template:
    variables:
     KUBERNETES_CPU_LIMIT: 8
     KUBERNETES_CPU_REQUEST: 4
     KUBERNETES_MEMORY_LIMIT: 8Gi
     CACHE_FALLBACK_KEY: master
     BUILD_DIR: build
     INSTALL_DIR: install

